data_tag = [
    ['C++'],
    ['C'],
    ['C#'],
    ['Java'],
    ['JavaScript'],
    ['Golang'],
    ['Assembly'],
    ['Python'],    
    ['Kotlin'],    
    ['HTML'],    
    ['CSS'],    
    ['Clojure'],    
    ['Haskell'],    
    ['Matlab'],    
    ['Prolog'],    
    ['Swift'],    
    ['Rust'],    
    ['Mojo'],    
    ['Rust'],    
    ['MSSQL'],    
    ['MySQL'],    
    ['PostgreSQL'],    
    ['NeO4j'],    
    ['3D'],    
    ['Blender'],    
    ['Компьютерные сети'],    
    ['Компьютерная графика'],    
    ['Веб-разработка'],    
    ['Игры'],    
    ['Администрирования'],    
    ['Linux'],    
    ['Windows'],    
    ['Машинное обучение'],    
    ['Анализ данных'],    
    ['Алгоритмы'],    
    ['Django'],    
    ['Docker'],    
    ['Kubernetus'],    
    ['CMake'],    
    ['Make'],    
    ['Maven'],    
    ['Anacond'],    
    ['pip'],    
    ['bash'],    
    ['1C'] 
]